### ISSUE TITLE
Feature 1: Parking spot reservation

### ISSUE THREAD

**Issue by dagmawitensay** [dagiTensay/Parking-Spot-reservation#1]
The parking spot reservation feature allows users to reserve a parking spot ahead of time using the mobile app. This feature is especially useful for busy areas where parking spots are limited and users want to ensure that they have a spot available when they arrive.

To use this feature, users can select the date and time they wish to reserve a spot, as well as the location where they want to park. The app will then display a list of available spots for the selected date and time at the chosen location.  This feature makes parking easier and more convenient for users, as they no longer have to drive around looking for an available spot.

**Comment by dagiTensay** [comment]
Implemented

**Comment by dagmawitensay** [comment]
Implemented
