### ISSUE TITLE
Feature 2: Booking a parking spot

### ISSUE THREAD

**Issue by dagmawitensay** [dagiTensay/Parking-Spot-reservation#2]
The booking the spot feature allows users to book a parking spot in advance using the mobile app. This feature is particularly helpful for users who need to park their vehicle for an extended period of time, such as when traveling or attending an event.
To use this feature, users can select the location where they wish to park, as well as the date and time range for their booking. The app will then display a list of available spots at the selected location for the chosen dates and times. Users can select the spot they want and make a booking .
Once a user has booked a spot, the parking space will be reserved for them for the entire duration of their booking. The user can then navigate to the location and park in the reserved spot. With this feature users can plan their route and park directly in their booked spot without wasting time and fuel searching for parking.

**Comment by dagiTensay** [comment]
Implemented with some some unfinished tasks.

**Comment by dagmawitensay** [comment]
Implemented with some some unfinished tasks.
